<template><div><h1 id="数组-2-2024-09-23" tabindex="-1"><a class="header-anchor" href="#数组-2-2024-09-23"><span>数组-2 2024/09/23</span></a></h1>
<blockquote>
<p>今日题目：<a href="https://leetcode.cn/problems/minimum-size-subarray-sum/description/" target="_blank" rel="noopener noreferrer">5. 长度最小的子数组</a> <a href="https://leetcode.cn/problems/spiral-matrix-ii/description/" target="_blank" rel="noopener noreferrer">6. 螺旋矩阵 Ⅱ</a></p>
</blockquote>
<h2 id="长度最小的子数组" tabindex="-1"><a class="header-anchor" href="#长度最小的子数组"><span>长度最小的子数组</span></a></h2>
<h3 id="题目说明" tabindex="-1"><a class="header-anchor" href="#题目说明"><span>题目说明</span></a></h3>
<font style="color:rgb(44, 62, 80);">给定一个含有 n 个正整数的数组和一个正整数 s ，找出该数组中满足其和 ≥ s 的长度最小的 连续 子数组，并返回其长度。如果不存在符合条件的子数组，返回 0。</font><h3 id="常规解法" tabindex="-1"><a class="header-anchor" href="#常规解法"><span>常规解法</span></a></h3>
<div class="language-python line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="py" data-title="py"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-python"><code><span class="line"><span class="line"><span style="color:#81A1C1">class</span><span style="color:#8FBCBB"> Solution</span><span style="color:#ECEFF4">:</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    def</span><span style="color:#88C0D0"> minSubArrayLen</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">self</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> s</span><span style="color:#ECEFF4">:</span><span style="color:#88C0D0"> int</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> nums</span><span style="color:#ECEFF4">:</span><span style="color:#D8DEE9FF"> List</span><span style="color:#ECEFF4">[</span><span style="color:#88C0D0">int</span><span style="color:#ECEFF4">])</span><span style="color:#ECEFF4"> -></span><span style="color:#88C0D0"> int</span><span style="color:#ECEFF4">:</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">        l </span><span style="color:#81A1C1">=</span><span style="color:#88C0D0"> len</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">nums</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">        min_len </span><span style="color:#81A1C1">=</span><span style="color:#88C0D0"> float</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">'</span><span style="color:#A3BE8C">inf</span><span style="color:#ECEFF4">'</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        for</span><span style="color:#D8DEE9FF"> i </span><span style="color:#81A1C1">in</span><span style="color:#88C0D0"> range</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">l</span><span style="color:#ECEFF4">):</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            cur_sum </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 0</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            for</span><span style="color:#D8DEE9FF"> j </span><span style="color:#81A1C1">in</span><span style="color:#88C0D0"> range</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">i</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> l</span><span style="color:#ECEFF4">):</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                cur_sum </span><span style="color:#81A1C1">+=</span><span style="color:#D8DEE9FF"> nums</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">j</span><span style="color:#ECEFF4">]</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                if</span><span style="color:#D8DEE9FF"> cur_sum </span><span style="color:#81A1C1">>=</span><span style="color:#D8DEE9FF"> s</span><span style="color:#ECEFF4">:</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                    min_len </span><span style="color:#81A1C1">=</span><span style="color:#88C0D0"> min</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">min_len</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> j </span><span style="color:#81A1C1">-</span><span style="color:#D8DEE9FF"> i </span><span style="color:#81A1C1">+</span><span style="color:#B48EAD"> 1</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                    break</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        return</span><span style="color:#D8DEE9FF"> min_len </span><span style="color:#81A1C1">if</span><span style="color:#D8DEE9FF"> min_len </span><span style="color:#81A1C1">!=</span><span style="color:#88C0D0"> float</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">'</span><span style="color:#A3BE8C">inf</span><span style="color:#ECEFF4">'</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> else</span><span style="color:#B48EAD"> 0</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="优化解法-滑窗" tabindex="-1"><a class="header-anchor" href="#优化解法-滑窗"><span>优化解法(滑窗)</span></a></h3>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> int</span><span style="color:#88C0D0"> minSubArrayLen</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9FF"> target</span><span style="color:#ECEFF4">,</span><span style="color:#81A1C1"> int</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9FF"> nums</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    int</span><span style="color:#D8DEE9"> n</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> nums</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">length</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    int</span><span style="color:#D8DEE9"> left</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> sum </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    int</span><span style="color:#D8DEE9"> ans</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9FF"> n </span><span style="color:#81A1C1">+</span><span style="color:#B48EAD"> 1</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    // 先尝试扩张窗口，等到区间内总和大于等于target时再收缩</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    // 处理之后的长度相当于当前右端点的最小长度</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    for</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> right</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> right </span><span style="color:#81A1C1">&#x3C;</span><span style="color:#D8DEE9FF"> n</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> right</span><span style="color:#81A1C1">++</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">        // 扩张窗口</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">        sum </span><span style="color:#81A1C1">+=</span><span style="color:#D8DEE9FF"> nums</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">right</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">        // 收缩窗口</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        while</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">sum </span><span style="color:#81A1C1">>=</span><span style="color:#D8DEE9FF"> target</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            ans </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">min</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">right </span><span style="color:#81A1C1">-</span><span style="color:#D8DEE9FF"> left </span><span style="color:#81A1C1">+</span><span style="color:#B48EAD"> 1</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> ans</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            sum </span><span style="color:#81A1C1">-=</span><span style="color:#D8DEE9FF"> nums</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">left</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            left</span><span style="color:#81A1C1">++;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">ans </span><span style="color:#81A1C1">==</span><span style="color:#D8DEE9FF"> n </span><span style="color:#81A1C1">+</span><span style="color:#B48EAD"> 1</span><span style="color:#81A1C1">?</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1"> :</span><span style="color:#D8DEE9FF"> ans</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="相关题目" tabindex="-1"><a class="header-anchor" href="#相关题目"><span>相关题目</span></a></h3>
<ul>
<li>[x] <a href="https://leetcode.cn/problems/fruit-into-baskets/" target="_blank" rel="noopener noreferrer"><font style="color:rgb(44, 62, 80);">904.水果成篮</font></a><font style="color:rgb(44, 62, 80);">(滑窗)</font></li>
<li>[x] <a href="https://leetcode.cn/problems/minimum-window-substring/" target="_blank" rel="noopener noreferrer"><font style="color:rgb(44, 62, 80);">76.最小覆盖子串</font></a><font style="color:rgb(44, 62, 80);">(</font><strong><font style="color:rgb(44, 62, 80);">最短型</font></strong><font style="color:rgb(44, 62, 80);">滑窗)</font></li>
</ul>
<h2 id="水果成篮" tabindex="-1"><a class="header-anchor" href="#水果成篮"><span>水果成篮</span></a></h2>
<h3 id="滑窗思路解析" tabindex="-1"><a class="header-anchor" href="#滑窗思路解析"><span>滑窗思路解析</span></a></h3>
<p>这题的意思实际上是让我们求**只出现****<u>两种</u>**<strong>字符的最大子区间长度</strong>。</p>
<p>那么可以用一个变量来存储当前区间内存在的字符种类数量，并且使用哈希表来存储各字符在当前窗口内出现的次数。</p>
<p>所以收缩窗口的条件为：<code v-pre>kind &gt; 2</code></p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">class</span><span style="color:#8FBCBB"> Solution</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#81A1C1"> int</span><span style="color:#88C0D0"> totalFruit</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">int</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9"> fruits</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">        // 求只出现两种字符的最大子区间长度</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">        // 使用哈希表来维护当前区间出现的字符情况</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#D8DEE9"> n</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> fruits</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">length</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9"> counts</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#81A1C1"> int</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">n</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#D8DEE9"> ans</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> kind </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#D8DEE9"> left</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        for</span><span style="color:#ECEFF4"> (</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> right</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> right </span><span style="color:#81A1C1">&#x3C;</span><span style="color:#D8DEE9FF"> n</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> right</span><span style="color:#81A1C1">++</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">counts</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">fruits</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">right</span><span style="color:#ECEFF4">]]</span><span style="color:#81A1C1"> ==</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">                // 统计当前持有的水果总类</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                kind</span><span style="color:#81A1C1">++;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            }</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">            // 扩张窗口</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            counts</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">fruits</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">right</span><span style="color:#ECEFF4">]]</span><span style="color:#81A1C1">++;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">            // 种类大于等于3时，触发窗口收缩</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            while</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">kind </span><span style="color:#81A1C1">></span><span style="color:#B48EAD"> 2</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                counts</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">fruits</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">left</span><span style="color:#ECEFF4">]]</span><span style="color:#81A1C1">--;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">counts</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">fruits</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">left</span><span style="color:#ECEFF4">]]</span><span style="color:#81A1C1"> ==</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                    kind</span><span style="color:#81A1C1">--;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">                }</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                left</span><span style="color:#81A1C1">++;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            }</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">            // 统计长度</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            ans </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">max</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">right </span><span style="color:#81A1C1">-</span><span style="color:#D8DEE9FF"> left </span><span style="color:#81A1C1">+</span><span style="color:#B48EAD"> 1</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> ans</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        return</span><span style="color:#D8DEE9FF"> ans</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="最小覆盖子串" tabindex="-1"><a class="header-anchor" href="#最小覆盖子串"><span>最小覆盖子串</span></a></h2>
<blockquote>
<p>不愧是困难题，真的有点复杂</p>
</blockquote>
<h3 id="题目说明-1" tabindex="-1"><a class="header-anchor" href="#题目说明-1"><span>题目说明</span></a></h3>
<p>给你一个字符串 <code v-pre>s</code> 、一个字符串 <code v-pre>t</code> 。返回 <code v-pre>s</code> 中涵盖 <code v-pre>t</code> 所有字符的最小子串。如果 <code v-pre>s</code> 中不存在涵盖 <code v-pre>t</code> 所有字符的子串，则返回空字符串 <code v-pre>&quot;&quot;</code> 。</p>
<p><strong>注意：</strong></p>
<ul>
<li>对于 <code v-pre>t</code> 中重复字符，我们寻找的子字符串中该字符数量必须<strong>不少于</strong> <code v-pre>t</code> 中该字符数量。</li>
<li>如果 <code v-pre>s</code> 中存在这样的子串，我们保证它是唯一的答案。</li>
</ul>
<h3 id="概念-字符串涵盖" tabindex="-1"><a class="header-anchor" href="#概念-字符串涵盖"><span>概念：字符串涵盖</span></a></h3>
<p>对于这道题目来说，字符串涵盖这个概念实际上就是题目的注意点 1。</p>
<p>例如示例一中 <code v-pre>s</code> 的子串 <code v-pre>BANC</code> 中每个字符出现的频率都大于等于 <code v-pre>t</code> 串中的频率，这就叫<strong>字符串涵盖</strong>。</p>
<h3 id="基本思路分析" tabindex="-1"><a class="header-anchor" href="#基本思路分析"><span>基本思路分析</span></a></h3>
<p>在了解了<a href="#F7jZz">涵盖</a>的概念之后，我们可以把题目要求转换为如下的描述：</p>
<blockquote>
<p>给定两个字符串 <code v-pre>s</code> <code v-pre>t</code> ，返回 <code v-pre>s</code> 中涵盖字符串 <code v-pre>t</code> 的<strong>最小</strong>子串。</p>
</blockquote>
<p>也许可以尝试用<strong>最短型滑窗</strong>的思路来解决这道问题。</p>
<p>可以确定<strong>收缩</strong>条件：当前窗口内的字符串涵盖字符串 <code v-pre>t</code></p>
<blockquote>
<p>Q：如何表示涵盖条件呢？</p>
</blockquote>
<p>在字符串涵盖这一概念的定义中， 其实已经说明了一个最直接的判断方法：</p>
<p>判断字符串中的<strong>每个字符出现频率</strong>都<strong>大于等于</strong>被涵盖字符串中的频率。</p>
<p>字符出现的频率可以用哈希表记录，在扩张/收缩时进行修改记录。</p>
<p>由此，我们可以得到解题的基本思路：</p>
<ol>
<li>初始化</li>
<li>统计 <code v-pre>t</code> 字符串中各字符出现的频率</li>
<li>枚举右端点，尝试进行窗口扩张</li>
<li>若满足涵盖条件，则尝试进行窗口收缩，并更新答案</li>
<li>返回答案对应窗口内的字符串</li>
</ol>
<h3 id="show-me-the-code" tabindex="-1"><a class="header-anchor" href="#show-me-the-code"><span>Show me the code!</span></a></h3>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">class</span><span style="color:#8FBCBB"> Solution</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#8FBCBB"> String</span><span style="color:#88C0D0"> minWindow</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9"> S</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> String</span><span style="color:#D8DEE9"> t</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        char</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9"> s</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> S</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">toCharArray</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#D8DEE9"> m</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> s</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">length</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#D8DEE9"> ansLeft</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> -</span><span style="color:#B48EAD">1</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#D8DEE9"> ansRight</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9FF"> m</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#D8DEE9"> left</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9"> cntS</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#81A1C1"> int</span><span style="color:#ECEFF4">[</span><span style="color:#B48EAD">128</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // s 子串字母的出现次数</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        int</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9"> cntT</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#81A1C1"> int</span><span style="color:#ECEFF4">[</span><span style="color:#B48EAD">128</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // t 中字母的出现次数</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        for</span><span style="color:#ECEFF4"> (</span><span style="color:#81A1C1">char</span><span style="color:#D8DEE9"> c</span><span style="color:#81A1C1"> :</span><span style="color:#D8DEE9"> t</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">toCharArray</span><span style="color:#ECEFF4">())</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            cntT</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">c</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1">++;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        for</span><span style="color:#ECEFF4"> (</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> right</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> right </span><span style="color:#81A1C1">&#x3C;</span><span style="color:#D8DEE9FF"> m</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> right</span><span style="color:#81A1C1">++</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span><span style="color:#616E88"> // 移动子串右端点</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">            cntS</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">s</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">right</span><span style="color:#ECEFF4">]]</span><span style="color:#81A1C1">++;</span><span style="color:#616E88"> // 右端点字母移入子串</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            while</span><span style="color:#ECEFF4"> (</span><span style="color:#88C0D0">isCovered</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">cntS</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> cntT</span><span style="color:#ECEFF4">))</span><span style="color:#ECEFF4"> {</span><span style="color:#616E88"> // 涵盖</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">right </span><span style="color:#81A1C1">-</span><span style="color:#D8DEE9FF"> left </span><span style="color:#81A1C1">&#x3C;</span><span style="color:#D8DEE9FF"> ansRight </span><span style="color:#81A1C1">-</span><span style="color:#D8DEE9FF"> ansLeft</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span><span style="color:#616E88"> // 找到更短的子串</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                    ansLeft </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9FF"> left</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // 记录此时的左右端点</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                    ansRight </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9FF"> right</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">                }</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">                cntS</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">s</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">left</span><span style="color:#81A1C1">++</span><span style="color:#ECEFF4">]]</span><span style="color:#81A1C1">--;</span><span style="color:#616E88"> // 左端点字母移出子串</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        return</span><span style="color:#D8DEE9FF"> ansLeft </span><span style="color:#81A1C1">&#x3C;</span><span style="color:#B48EAD"> 0</span><span style="color:#81A1C1"> ?</span><span style="color:#ECEFF4"> ""</span><span style="color:#81A1C1"> :</span><span style="color:#D8DEE9"> S</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">substring</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">ansLeft</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> ansRight </span><span style="color:#81A1C1">+</span><span style="color:#B48EAD"> 1</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    /**</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">     * 判断是否涵盖</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">     */</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    private</span><span style="color:#81A1C1"> boolean</span><span style="color:#88C0D0"> isCovered</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">int</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9"> cntS</span><span style="color:#ECEFF4">,</span><span style="color:#81A1C1"> int</span><span style="color:#ECEFF4">[]</span><span style="color:#D8DEE9"> cntT</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        for</span><span style="color:#ECEFF4"> (</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> i</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> '</span><span style="color:#A3BE8C">A</span><span style="color:#ECEFF4">'</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> i </span><span style="color:#81A1C1">&#x3C;=</span><span style="color:#ECEFF4"> '</span><span style="color:#A3BE8C">Z</span><span style="color:#ECEFF4">'</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> i</span><span style="color:#81A1C1">++</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">cntS</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">i</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1"> &#x3C;</span><span style="color:#D8DEE9FF"> cntT</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">i</span><span style="color:#ECEFF4">])</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                return</span><span style="color:#81A1C1"> false;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        for</span><span style="color:#ECEFF4"> (</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> i</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> '</span><span style="color:#A3BE8C">a</span><span style="color:#ECEFF4">'</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> i </span><span style="color:#81A1C1">&#x3C;=</span><span style="color:#ECEFF4"> '</span><span style="color:#A3BE8C">z</span><span style="color:#ECEFF4">'</span><span style="color:#81A1C1">;</span><span style="color:#D8DEE9FF"> i</span><span style="color:#81A1C1">++</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">            if</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">cntS</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">i</span><span style="color:#ECEFF4">]</span><span style="color:#81A1C1"> &#x3C;</span><span style="color:#D8DEE9FF"> cntT</span><span style="color:#ECEFF4">[</span><span style="color:#D8DEE9FF">i</span><span style="color:#ECEFF4">])</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                return</span><span style="color:#81A1C1"> false;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">            }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">        return</span><span style="color:#81A1C1"> true;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="滑窗总结" tabindex="-1"><a class="header-anchor" href="#滑窗总结"><span>滑窗总结</span></a></h2>
<p>滑窗的一般思路如下：</p>
<ol>
<li>初始化状态(根据枚举条件来，例如枚左移右等)</li>
<li>让滑窗<strong>扩张</strong>(移动端点)</li>
<li>根据限制条件来<strong>收缩</strong>滑窗</li>
<li>在移动过程中(视具体情况而定)更新答案</li>
</ol>
<blockquote>
<p>更新: 2024-09-23 12:18:27<br>
原文: <a href="https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/xr4nuqrosfegymfd" target="_blank" rel="noopener noreferrer">https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/xr4nuqrosfegymfd</a></p>
</blockquote>
</div></template>


