<template><div><h1 id="lec2-shell-tools" tabindex="-1"><a class="header-anchor" href="#lec2-shell-tools"><span>Lec2 Shell Tools</span></a></h1>
<ol>
<li>
<font style="color:rgb(0, 0, 0);">阅读 </font>`<font style="color:rgb(0, 0, 0);">man ls</font>`<font style="color:rgb(0, 0, 0);"> ，然后使用 </font>`<font style="color:rgb(0, 0, 0);">ls</font>`<font style="color:rgb(0, 0, 0);"> 命令进行如下操作：</font></li>
</ol>
<ul>
<li>
<font style="color:rgb(0, 0, 0);">所有文件（包括隐藏文件）</font></li>
<li>
<font style="color:rgb(0, 0, 0);">文件打印以人类可以理解的格式输出 (例如，使用 454M 而不是 454279954)</font></li>
<li>
<font style="color:rgb(0, 0, 0);">文件以最近访问顺序排序</font></li>
<li>
<font style="color:rgb(0, 0, 0);">以彩色文本显示输出结果</font></li>
</ul>
<div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-bash"><code><span class="line"><span class="line"><span style="color:#616E88"># 获取当前目录下所有文件</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">$</span><span style="color:#A3BE8C"> ls</span><span style="color:#A3BE8C"> -a</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 以人类可以理解的(长)格式输出</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">$</span><span style="color:#A3BE8C"> ls</span><span style="color:#A3BE8C"> -lh</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># drwxrwxr-x 2 johnson johnson 4.0K  9月 13 16:16 bar</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 以最近访问顺序排序，使用sort选项</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">$</span><span style="color:#A3BE8C"> ls</span><span style="color:#D8DEE9FF"> (--sort=)-t</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># sort选项可选参数值：</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># none: -U, size: -S, time: -t, version: -v, extension: -X</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 以彩色文本输出结果，使用color选项</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">$</span><span style="color:#A3BE8C"> ls</span><span style="color:#A3BE8C"> -lh</span><span style="color:#A3BE8C"> --color=auto</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li>
<font style="color:rgb(0, 0, 0);">编写两个 bash 函数 </font>`<font style="color:rgb(0, 0, 0);">marco</font>`<font style="color:rgb(0, 0, 0);"> 和 </font>`<font style="color:rgb(0, 0, 0);">polo</font>`<font style="color:rgb(0, 0, 0);"> 执行下面的操作。   </li>
</ol>
</font><font style="color:rgb(0, 0, 0);">每当你执行 </font>`<font style="color:rgb(0, 0, 0);">marco</font>`<font style="color:rgb(0, 0, 0);"> 时，当前的工作目录应当以某种形式保存。  
</font><font style="color:rgb(0, 0, 0);">当执行 </font>`<font style="color:rgb(0, 0, 0);">polo</font>`<font style="color:rgb(0, 0, 0);"> 时，无论现在处在什么目录下，都应当 </font>`<font style="color:rgb(0, 0, 0);">cd</font>`<font style="color:rgb(0, 0, 0);"> 回到当时执行 </font>`<font style="color:rgb(0, 0, 0);">marco</font>`<font style="color:rgb(0, 0, 0);"> 的目录。   
</font><font style="color:rgb(0, 0, 0);">为了方便 debug，你可以把代码写在单独的文件 </font>`<font style="color:rgb(0, 0, 0);">marco.sh</font>`<font style="color:rgb(0, 0, 0);"> 中，并通过 </font>`<font style="color:rgb(0, 0, 0);">source marco.sh</font>`<font style="color:rgb(0, 0, 0);"> 命令，（重新）加载函数。</font>
<div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-bash"><code><span class="line"><span class="line"><span style="color:#616E88"># marco.sh</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 设置shebang</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">#!/bin/sh</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">marco</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  echo</span><span style="color:#ECEFF4"> $(</span><span style="color:#88C0D0">pwd</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> ></span><span style="color:#A3BE8C"> ~/tmp/marco_history.txt</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># polo.sh</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">#!/bin/sh</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">polo</span><span style="color:#ECEFF4"> ()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  cd</span><span style="color:#ECEFF4"> $(</span><span style="color:#88C0D0">cat</span><span style="color:#A3BE8C"> ~/tmp/marco_history.txt</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> ||</span><span style="color:#88C0D0"> exit</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  echo</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">Now cd to </span><span style="color:#ECEFF4">$(</span><span style="color:#88C0D0">cat</span><span style="color:#A3BE8C"> ~/tmp/marco_history.txt</span><span style="color:#ECEFF4">)</span><span style="color:#A3BE8C">...</span><span style="color:#ECEFF4">"</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="3">
<li>
<font style="color:rgb(0, 0, 0);">假设您有一个命令，它很少出错。因此为了在出错时能够对其进行调试，需要花费大量的时间重现错误并捕获输出。 编写一段 bash 脚本，运行如下的脚本直到它出错，将它的标准输出和标准错误流记录到文件，并在最后输出所有内容。   
</li>
</ol>
</font>**<font style="color:rgb(0, 0, 0);">加分项：报告脚本在失败前共运行了多少次。</font>**
<div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-bash"><code><span class="line"><span class="line"><span style="color:#616E88"> #!/usr/bin/env bash</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9"> n</span><span style="color:#81A1C1">=</span><span style="color:#ECEFF4">$((</span><span style="color:#88C0D0"> RANDOM</span><span style="color:#A3BE8C"> %</span><span style="color:#B48EAD"> 100</span><span style="color:#ECEFF4"> ))</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1"> if</span><span style="color:#ECEFF4"> [[</span><span style="color:#D8DEE9FF"> n </span><span style="color:#81A1C1">-eq</span><span style="color:#B48EAD"> 42</span><span style="color:#ECEFF4"> ]]</span><span style="color:#81A1C1">;</span><span style="color:#81A1C1"> then</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    # 重定向信息至错误流</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    echo</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">Something went wrong</span><span style="color:#ECEFF4">"</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    >&#x26;2</span><span style="color:#88C0D0"> echo</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">The error was using magic numbers</span><span style="color:#ECEFF4">"</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    exit</span><span style="color:#B48EAD"> 1</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1"> fi</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0"> echo</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">Everything went according to plan</span><span style="color:#ECEFF4">"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-bash"><code><span class="line"><span class="line"><span style="color:#616E88"># 假设题给代码存储在 example.sh 文件中</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 脚本代码文件为 output.sh</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 养成好习惯，先写shebang</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">#!/usr/bin/env bash</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">count</span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C">0</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">echo</span><span style="color:#81A1C1"> ></span><span style="color:#A3BE8C"> output.log</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 不出错就一直运行下去</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">while</span><span style="color:#88C0D0"> true</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">do</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">  # &#x26;>>符号用于同时将输出重定向(>>)并让命令在后台运行(&#x26;)</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  ./example.sh</span><span style="color:#ECEFF4"> &#x26;</span><span style="color:#81A1C1">>></span><span style="color:#D8DEE9FF"> output.log</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  ((</span><span style="color:#D8DEE9">count</span><span style="color:#81A1C1">++</span><span style="color:#ECEFF4">))</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  if</span><span style="color:#ECEFF4"> [</span><span style="color:#ECEFF4"> "</span><span style="color:#81A1C1">$?</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1"> -ne</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4"> ]</span><span style="color:#81A1C1">;</span><span style="color:#81A1C1"> then</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    cat</span><span style="color:#A3BE8C"> output.log</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    echo</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">The script runs for </span><span style="color:#D8DEE9">$count</span><span style="color:#A3BE8C"> time(s)</span><span style="color:#ECEFF4">"</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    break</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  fi</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">done</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="4">
<li>
<font style="color:rgb(0, 0, 0);">本节课我们讲解的 </font>`<font style="color:rgb(0, 0, 0);">find</font>`<font style="color:rgb(0, 0, 0);"> 命令中的 </font>`<font style="color:rgb(0, 0, 0);">-exec</font>`<font style="color:rgb(0, 0, 0);"> 参数非常强大，它可以对我们查找的文件进行操作。但是，如果我们要对所有文件进行操作呢？例如创建一个 zip 压缩文件？我们已经知道，命令行可以从参数或标准输入接受输入。在用管道连接命令时，我们将标准输出和标准输入连接起来，但是有些命令，例如 </font>`<font style="color:rgb(0, 0, 0);">tar</font>`<font style="color:rgb(0, 0, 0);"> 则需要从参数接受输入。这里我们可以使用 </font>[<font style="color:rgb(0, 0, 0);">xargs</font>](https://man7.org/linux/man-pages/man1/xargs.1.html)<font style="color:rgb(0, 0, 0);"> 命令，它可以使用标准输入中的内容作为参数。 例如 </font>`<font style="color:rgb(0, 0, 0);">ls | xargs rm</font>`<font style="color:rgb(0, 0, 0);"> 会删除当前目录中的所有文件。</font></li>
</ol>
<font style="color:rgb(0, 0, 0);">您的任务是编写一个命令，它可以递归地查找文件夹中所有的 HTML 文件，并将它们压缩成 zip 文件。注意，即使文件名中包含空格，您的命令也应该能够正确执行（提示：查看 </font>`<font style="color:rgb(0, 0, 0);">xargs</font>`<font style="color:rgb(0, 0, 0);"> 的参数 </font>`<font style="color:rgb(0, 0, 0);">-d</font>`<font style="color:rgb(0, 0, 0);">)</font><div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-bash"><code><span class="line"><span class="line"><span style="color:#88C0D0">This</span><span style="color:#A3BE8C"> manual</span><span style="color:#A3BE8C"> page</span><span style="color:#A3BE8C"> documents</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C"> GNU</span><span style="color:#A3BE8C"> version</span><span style="color:#A3BE8C"> of</span><span style="color:#A3BE8C"> xargs.</span><span style="color:#A3BE8C">  xargs</span><span style="color:#A3BE8C"> reads</span><span style="color:#A3BE8C"> items</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       from</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C"> standard</span><span style="color:#A3BE8C"> input,</span><span style="color:#A3BE8C"> delimited</span><span style="color:#A3BE8C"> by</span><span style="color:#A3BE8C"> blanks</span><span style="color:#D8DEE9FF"> (which  </span><span style="color:#A3BE8C">can</span><span style="color:#A3BE8C">  be</span><span style="color:#A3BE8C">  protected</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       with</span><span style="color:#A3BE8C">  double</span><span style="color:#A3BE8C"> or</span><span style="color:#A3BE8C"> single</span><span style="color:#A3BE8C"> quotes</span><span style="color:#A3BE8C"> or</span><span style="color:#A3BE8C"> a</span><span style="color:#A3BE8C"> backslash</span><span style="color:#D8DEE9FF">) or newlines, and executes</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       the</span><span style="color:#A3BE8C"> command</span><span style="color:#D8DEE9FF"> (default </span><span style="color:#A3BE8C">is</span><span style="color:#A3BE8C"> /bin/echo</span><span style="color:#D8DEE9FF">) one or more times with any  initial-</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       arguments</span><span style="color:#A3BE8C">  followed</span><span style="color:#A3BE8C">  by</span><span style="color:#A3BE8C"> items</span><span style="color:#A3BE8C"> read</span><span style="color:#A3BE8C"> from</span><span style="color:#A3BE8C"> standard</span><span style="color:#A3BE8C"> input.</span><span style="color:#A3BE8C">  Blank</span><span style="color:#A3BE8C"> lines</span><span style="color:#A3BE8C"> on</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       the</span><span style="color:#A3BE8C"> standard</span><span style="color:#A3BE8C"> input</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> ignored.</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">...</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">Because</span><span style="color:#A3BE8C"> Unix</span><span style="color:#A3BE8C"> filenames</span><span style="color:#A3BE8C"> can</span><span style="color:#A3BE8C"> contain</span><span style="color:#A3BE8C"> blanks</span><span style="color:#A3BE8C"> and</span><span style="color:#A3BE8C">  newlines,</span><span style="color:#A3BE8C">  this</span><span style="color:#A3BE8C">  default</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       behaviour</span><span style="color:#A3BE8C"> is</span><span style="color:#A3BE8C"> often</span><span style="color:#A3BE8C"> problematic</span><span style="color:#81A1C1">;</span><span style="color:#88C0D0"> filenames</span><span style="color:#A3BE8C"> containing</span><span style="color:#A3BE8C"> blanks</span><span style="color:#A3BE8C"> and/or</span><span style="color:#A3BE8C"> new‐</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       lines</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> incorrectly</span><span style="color:#A3BE8C"> processed</span><span style="color:#A3BE8C"> by</span><span style="color:#A3BE8C"> xargs.</span><span style="color:#A3BE8C">  In</span><span style="color:#A3BE8C"> these</span><span style="color:#A3BE8C">  situations</span><span style="color:#A3BE8C">  it</span><span style="color:#A3BE8C">  is</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       better</span><span style="color:#A3BE8C"> to</span><span style="color:#A3BE8C"> use</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C"> -0</span><span style="color:#A3BE8C"> option,</span><span style="color:#A3BE8C"> which</span><span style="color:#A3BE8C"> prevents</span><span style="color:#A3BE8C"> such</span><span style="color:#A3BE8C"> problems.</span><span style="color:#A3BE8C">   When</span><span style="color:#A3BE8C"> using</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       this</span><span style="color:#A3BE8C"> option</span><span style="color:#A3BE8C"> you</span><span style="color:#A3BE8C"> will</span><span style="color:#A3BE8C"> need</span><span style="color:#A3BE8C"> to</span><span style="color:#A3BE8C"> ensure</span><span style="color:#A3BE8C"> that</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C"> program</span><span style="color:#A3BE8C"> which</span><span style="color:#A3BE8C"> produces</span><span style="color:#A3BE8C"> the</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       input</span><span style="color:#A3BE8C">  for</span><span style="color:#A3BE8C">  xargs</span><span style="color:#A3BE8C">  also</span><span style="color:#A3BE8C">  uses</span><span style="color:#A3BE8C"> a</span><span style="color:#A3BE8C"> null</span><span style="color:#A3BE8C"> character</span><span style="color:#A3BE8C"> as</span><span style="color:#A3BE8C"> a</span><span style="color:#A3BE8C"> separator.</span><span style="color:#A3BE8C">  If</span><span style="color:#A3BE8C"> that</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">       program</span><span style="color:#A3BE8C"> is</span><span style="color:#A3BE8C"> GNU</span><span style="color:#A3BE8C"> find</span><span style="color:#A3BE8C"> for</span><span style="color:#A3BE8C"> example,</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C"> -print0</span><span style="color:#A3BE8C"> option</span><span style="color:#A3BE8C"> does</span><span style="color:#A3BE8C"> this</span><span style="color:#A3BE8C"> for</span><span style="color:#A3BE8C"> you.</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">...</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">OPTIONS</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">-0,</span><span style="color:#A3BE8C"> --null</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              Input</span><span style="color:#A3BE8C"> items</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> terminated</span><span style="color:#A3BE8C"> by</span><span style="color:#A3BE8C"> a</span><span style="color:#A3BE8C"> null</span><span style="color:#A3BE8C">  character</span><span style="color:#A3BE8C">  instead</span><span style="color:#A3BE8C">  of</span><span style="color:#A3BE8C">  by</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              whitespace,</span><span style="color:#A3BE8C">  and</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C"> quotes</span><span style="color:#A3BE8C"> and</span><span style="color:#A3BE8C"> backslash</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> not</span><span style="color:#A3BE8C"> special</span><span style="color:#D8DEE9FF"> (every</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              character</span><span style="color:#A3BE8C"> is</span><span style="color:#A3BE8C"> taken</span><span style="color:#A3BE8C"> literally</span><span style="color:#D8DEE9FF">).  Disables the </span><span style="color:#81A1C1">end</span><span style="color:#D8DEE9FF"> of file string,</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              which</span><span style="color:#A3BE8C">  is</span><span style="color:#A3BE8C">  treated</span><span style="color:#A3BE8C">  like</span><span style="color:#A3BE8C">  any</span><span style="color:#A3BE8C"> other</span><span style="color:#A3BE8C"> argument.</span><span style="color:#A3BE8C">  Useful</span><span style="color:#A3BE8C"> when</span><span style="color:#A3BE8C"> input</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              items</span><span style="color:#A3BE8C"> might</span><span style="color:#A3BE8C"> contain</span><span style="color:#A3BE8C"> white</span><span style="color:#A3BE8C"> space,</span><span style="color:#A3BE8C"> quote</span><span style="color:#A3BE8C">  marks,</span><span style="color:#A3BE8C">  or</span><span style="color:#A3BE8C">  backslashes.</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              The</span><span style="color:#A3BE8C">  GNU</span><span style="color:#A3BE8C">  find</span><span style="color:#A3BE8C">  -print0</span><span style="color:#A3BE8C">  option</span><span style="color:#A3BE8C"> produces</span><span style="color:#A3BE8C"> input</span><span style="color:#A3BE8C"> suitable</span><span style="color:#A3BE8C"> for</span><span style="color:#A3BE8C"> this</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              mode.</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">--delimiter</span><span style="color:#81A1C1">=</span><span style="color:#A3BE8C">delim,</span><span style="color:#88C0D0"> -d</span><span style="color:#A3BE8C"> delim</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              Input</span><span style="color:#A3BE8C"> items</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> terminated</span><span style="color:#A3BE8C">  by</span><span style="color:#A3BE8C">  the</span><span style="color:#A3BE8C">  specified</span><span style="color:#A3BE8C">  character.</span><span style="color:#A3BE8C">   The</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              specified</span><span style="color:#A3BE8C"> delimiter</span><span style="color:#A3BE8C"> may</span><span style="color:#A3BE8C"> be</span><span style="color:#A3BE8C"> a</span><span style="color:#A3BE8C"> single</span><span style="color:#A3BE8C"> character,</span><span style="color:#A3BE8C"> a</span><span style="color:#A3BE8C"> C-style</span><span style="color:#A3BE8C"> charac‐</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              ter</span><span style="color:#A3BE8C"> escape</span><span style="color:#A3BE8C"> such</span><span style="color:#A3BE8C"> as</span><span style="color:#EBCB8B"> \n</span><span style="color:#A3BE8C">,</span><span style="color:#A3BE8C"> or</span><span style="color:#A3BE8C"> an</span><span style="color:#A3BE8C"> octal</span><span style="color:#A3BE8C"> or</span><span style="color:#A3BE8C"> hexadecimal</span><span style="color:#A3BE8C">  escape</span><span style="color:#A3BE8C">  code.</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              Octal</span><span style="color:#A3BE8C">  and</span><span style="color:#A3BE8C">  hexadecimal</span><span style="color:#A3BE8C">  escape</span><span style="color:#A3BE8C">  codes</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> understood</span><span style="color:#A3BE8C"> as</span><span style="color:#A3BE8C"> for</span><span style="color:#A3BE8C"> the</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              printf</span><span style="color:#A3BE8C"> command.</span><span style="color:#A3BE8C">   Multibyte</span><span style="color:#A3BE8C"> characters</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> not</span><span style="color:#A3BE8C"> supported.</span><span style="color:#A3BE8C">   When</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              processing</span><span style="color:#A3BE8C">  the</span><span style="color:#A3BE8C"> input,</span><span style="color:#A3BE8C"> quotes</span><span style="color:#A3BE8C"> and</span><span style="color:#A3BE8C"> backslash</span><span style="color:#A3BE8C"> are</span><span style="color:#A3BE8C"> not</span><span style="color:#A3BE8C"> special</span><span style="color:#81A1C1">;</span><span style="color:#88C0D0"> ev‐</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              ery</span><span style="color:#A3BE8C"> character</span><span style="color:#A3BE8C"> in</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C"> input</span><span style="color:#A3BE8C"> is</span><span style="color:#A3BE8C"> taken</span><span style="color:#A3BE8C"> literally.</span><span style="color:#A3BE8C">   The</span><span style="color:#A3BE8C">  -d</span><span style="color:#A3BE8C">  option</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              disables</span><span style="color:#A3BE8C"> any</span><span style="color:#A3BE8C"> end-of-file</span><span style="color:#A3BE8C"> string,</span><span style="color:#A3BE8C"> which</span><span style="color:#A3BE8C"> is</span><span style="color:#A3BE8C"> treated</span><span style="color:#A3BE8C"> like</span><span style="color:#A3BE8C"> any</span><span style="color:#A3BE8C"> other</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              argument.</span><span style="color:#A3BE8C">  You</span><span style="color:#A3BE8C"> can</span><span style="color:#A3BE8C"> use</span><span style="color:#A3BE8C"> this</span><span style="color:#A3BE8C"> option</span><span style="color:#A3BE8C"> when</span><span style="color:#A3BE8C"> the</span><span style="color:#A3BE8C">  input</span><span style="color:#A3BE8C">  consists</span><span style="color:#A3BE8C">  of</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              simply</span><span style="color:#A3BE8C">  newline-separated</span><span style="color:#A3BE8C">  items,</span><span style="color:#A3BE8C">  although</span><span style="color:#A3BE8C">  it</span><span style="color:#A3BE8C"> is</span><span style="color:#A3BE8C"> almost</span><span style="color:#A3BE8C"> always</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              better</span><span style="color:#A3BE8C"> to</span><span style="color:#A3BE8C"> design</span><span style="color:#A3BE8C"> your</span><span style="color:#A3BE8C"> program</span><span style="color:#A3BE8C"> to</span><span style="color:#A3BE8C"> use</span><span style="color:#A3BE8C"> --null</span><span style="color:#A3BE8C"> where</span><span style="color:#A3BE8C"> this</span><span style="color:#A3BE8C"> is</span><span style="color:#A3BE8C"> possi‐</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">              ble.</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>先把要做的事情拆解一下：</p>
<ul>
<li>查找当前文件夹中所有的 HTML 文件 <code v-pre>find . -name '*.html'</code></li>
<li>使用 <code v-pre>tar</code> 将这些 HTML 文件压缩成 zip 文件(创建 <code v-pre>archive</code>)，将找到的 HTML 文件作为输入流</li>
</ul>
<p>查找一下 <code v-pre>tar</code> 命令的 man 手册就可以完成本题了：</p>
<div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-bash"><code><span class="line"><span class="line"><span style="color:#88C0D0">find</span><span style="color:#A3BE8C"> .</span><span style="color:#A3BE8C"> -type</span><span style="color:#A3BE8C"> f</span><span style="color:#A3BE8C"> -name</span><span style="color:#ECEFF4"> '</span><span style="color:#A3BE8C">*.html</span><span style="color:#ECEFF4">'</span><span style="color:#81A1C1"> |</span><span style="color:#88C0D0"> xargs</span><span style="color:#A3BE8C"> -d</span><span style="color:#ECEFF4"> '</span><span style="color:#A3BE8C">\n</span><span style="color:#ECEFF4">'</span><span style="color:#A3BE8C"> tar</span><span style="color:#A3BE8C"> -cvf</span><span style="color:#A3BE8C"> htmls.zip</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page4.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page8.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page7.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page3.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page9.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page1.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page5.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page6.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page2.html</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># 验证命令是否生效</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">tar</span><span style="color:#A3BE8C"> -tf</span><span style="color:#A3BE8C"> htmls.zip</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page4.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page8.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page7.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page3.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page9.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page1.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page5.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page6.html</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"># ./web-page2.html</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="5">
<li>
<font style="color:rgb(0, 0, 0);">（进阶）编写一个命令或脚本递归的查找文件夹中</font>**<font style="color:rgb(0, 0, 0);">最近使用的</font>****<u><font style="color:rgb(0, 0, 0);">一个</font></u>****<font style="color:rgb(0, 0, 0);">文件</font>**<font style="color:rgb(0, 0, 0);">。  </li>
</ol>
</font><font style="color:rgb(0, 0, 0);">更通用的做法，你可以按照</font>**<font style="color:rgb(0, 0, 0);">最近的使用时间排序</font>**<font style="color:rgb(0, 0, 0);">列出文件吗？(其实这句话是个提示)</font>
<font style="color:rgb(0, 0, 0);">要找出最近使用的一个文件，可以这么办：</font><ul>
<li>先找出所有文件信息(递归地查找，<code v-pre>find</code> 命令就是这么干的)</li>
<li>按照修改时间排序并展示(这种展示的活应该需要 <code v-pre>ls</code> 命令来做，按照时间排序可以使用 <code v-pre>-t</code>标志)</li>
<li>只展示第一条信息(<code v-pre>head -1</code>)</li>
</ul>
<p>那么将上述命令组合起来就可以完成要求了</p>
<div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-bash"><code><span class="line"><span class="line"><span style="color:#88C0D0">find</span><span style="color:#A3BE8C"> .</span><span style="color:#A3BE8C"> -type</span><span style="color:#A3BE8C"> f</span><span style="color:#81A1C1"> |</span><span style="color:#88C0D0"> xargs</span><span style="color:#A3BE8C"> ls</span><span style="color:#A3BE8C"> -ltch</span><span style="color:#81A1C1"> |</span><span style="color:#88C0D0"> head</span><span style="color:#A3BE8C"> -1</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><font style="color:rgb(0, 0, 0);">按照</font>**<font style="color:rgb(0, 0, 0);">最近的使用时间</font>**<font style="color:rgb(0, 0, 0);">列出文件则更简单了，去掉上述命令中的 </font>`<font style="color:rgb(0, 0, 0);">head</font>`<font style="color:rgb(0, 0, 0);"> 命令即可。</font><blockquote>
<p>更新: 2024-09-15 15:57:31<br>
原文: <a href="https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/hnxrgvsdbtahfh91" target="_blank" rel="noopener noreferrer">https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/hnxrgvsdbtahfh91</a></p>
</blockquote>
</div></template>


