<template><div><h1 id="ostep-学习笔记-2-concurrency" tabindex="-1"><a class="header-anchor" href="#ostep-学习笔记-2-concurrency"><span>OSTEP 学习笔记-2 Concurrency</span></a></h1>
<blockquote>
<p>章节号: P25-27 Homework</p>
</blockquote>
<h2 id="atomic-operations" tabindex="-1"><a class="header-anchor" href="#atomic-operations"><span>Atomic Operations</span></a></h2>
<p>Atomic operations are one of the most powerful underlying techniques in building computer systems, from the computer architecture, to concurrent code, to file systems, database management systems, and even distributed systems.</p>
<p>The idea behind making a series of actions atomic is simply expressed with the phrase “<strong>all or nothing</strong>”; it should either appear as if <strong>all of the actions</strong> you wish to group together occurred, or that <strong>none of them</strong> occurred, with <strong>no in-between state visible</strong>. Sometimes, the grouping of many actions into a single atomic action is called a <strong>transaction(事务)</strong>, an idea developed in great detail in the world of databases and transaction processing.</p>
<h2 id="two-major-problem-on-concurrency-programming" tabindex="-1"><a class="header-anchor" href="#two-major-problem-on-concurrency-programming"><span>Two Major Problem on Concurrency Programming</span></a></h2>
<ul>
<li>Access to Shared Data (Crux: <strong>Uncontrolled</strong> Scheduling)</li>
<li>Waiting For Another Thread (e.g. A thread would sleep until the Disk I/O ends)</li>
</ul>
<h2 id="crux-of-concurrency" tabindex="-1"><a class="header-anchor" href="#crux-of-concurrency"><span>Crux of Concurrency</span></a></h2>
<p>THE CRUX: HOW TO SUPPORT SYNCHRONIZATION</p>
<p>What support do we need from the hardware in order to build useful synchronization primitives? What support do we need from the OS? How can we build these primitives correctly and efficiently? How can programs use them to get the desired results?</p>
<h2 id="key-concurrency-terms" tabindex="-1"><a class="header-anchor" href="#key-concurrency-terms"><span>Key Concurrency Terms</span></a></h2>
<blockquote>
<p>The key concurrency terms include these following items:</p>
<ul>
<li>CRITICAL SECTION (临界区域)</li>
<li>RACE CONDITION (静态条件)</li>
<li>INDETERMINATE (不确定的)</li>
<li>MUTUAL EXCLUSION (互斥)</li>
</ul>
</blockquote>
<p>These four terms are so central to concurrent code that we thought it worth while to call them out explicitly.</p>
<p>• A <strong>critical section</strong> is a piece of code that <strong>accesses a shared resource</strong>, usually a variable or data structure.</p>
<p>• A <strong>race condition</strong> (or data race [NM92]) arises if <strong><u>multiple threads</u></strong>** of execution enter the critical section ****<u>at roughly the same time</u>**; both attempt to update the shared data structure, leading to a surprising (and perhaps undesirable) outcome.</p>
<p>• An <strong>indeterminate</strong> program consists of <strong>one or more race conditions</strong>; the output of the program varies from run to run, depending on which threads ran when. The outcome is thus <strong>not deterministic</strong>, something we usually expect from computer systems.</p>
<p>• To avoid these problems, threads should use some kind of <strong>mutual exclusion</strong> primitives; doing so guarantees that <strong>only a single thread ever enters a critical section</strong>, thus <strong>avoiding races</strong>, and resulting in deterministic program outputs.</p>
<h2 id="crux-of-threads" tabindex="-1"><a class="header-anchor" href="#crux-of-threads"><span>Crux of Threads</span></a></h2>
<p>CRUX: HOW TO CREATE AND CONTROL THREADS</p>
<p>What interfaces should the OS present for thread creation and control? How should these interfaces be designed to enable ease of use as well as utility?</p>
<h3 id="thread-creation" tabindex="-1"><a class="header-anchor" href="#thread-creation"><span>Thread Creation</span></a></h3>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#5E81AC;font-weight:bold">#</span><span style="color:#81A1C1">include</span><span style="color:#ECEFF4"> &#x3C;</span><span style="color:#8FBCBB">pthread.h</span><span style="color:#ECEFF4">></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_create</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">thread</span><span style="color:#ECEFF4">,</span><span style="color:#616E88"> // Thread Identifier</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                   const</span><span style="color:#81A1C1"> pthread_attr_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">attr</span><span style="color:#ECEFF4">,</span><span style="color:#616E88"> // The thread's own attributes</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                   void</span><span style="color:#81A1C1"> *</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">*</span><span style="color:#D8DEE9FF">start_routine</span><span style="color:#ECEFF4">)(</span><span style="color:#81A1C1">void*</span><span style="color:#ECEFF4">),</span><span style="color:#616E88"> // Where to start the thread</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                   void</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">arg</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // The start-thread function's args</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="waiting-for-a-thread-to-complete" tabindex="-1"><a class="header-anchor" href="#waiting-for-a-thread-to-complete"><span>Waiting For a Thread to Complete</span></a></h3>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_join</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_t</span><span style="color:#D8DEE9"> __th</span><span style="color:#ECEFF4">,</span><span style="color:#616E88"> // Thread Identifier</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                 void</span><span style="color:#81A1C1"> **</span><span style="color:#D8DEE9">__thread_return</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // The exit value of the thread, if it's not NULL</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>注意：永远不要返回指向<strong>在线程调用栈中分配资源</strong>的指针。</p>
</blockquote>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#81A1C1">void</span><span style="color:#81A1C1"> *</span><span style="color:#88C0D0">mythread</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">void</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">arg</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">    myarg_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9FF">args </span><span style="color:#81A1C1">=</span><span style="color:#ECEFF4"> (</span><span style="color:#8FBCBB">myarg_t</span><span style="color:#81A1C1"> *</span><span style="color:#ECEFF4">)</span><span style="color:#D8DEE9FF"> arg</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    printf</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">%d %d</span><span style="color:#EBCB8B">\n</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> args</span><span style="color:#81A1C1">-></span><span style="color:#D8DEE9">a</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> args</span><span style="color:#81A1C1">-></span><span style="color:#D8DEE9">b</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">    myret_t</span><span style="color:#D8DEE9FF"> oops</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // ALLOCATED ON STACK: BAD!</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    oops</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">x</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 1</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    oops</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">y</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 2</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#ECEFF4"> (</span><span style="color:#81A1C1">void</span><span style="color:#81A1C1"> *</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> &#x26;</span><span style="color:#D8DEE9FF">oops</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>在这种情况下，变量 <code v-pre>oops</code> 被分配到 <code v-pre>mythread</code> 的堆栈中。不过，当它返回时，该值<strong>会被自动解除分配</strong>。在已解除分配的内容上进行操作是件非常危险的事情！</p>
</blockquote>
<h4 id="whether-to-use-join" tabindex="-1"><a class="header-anchor" href="#whether-to-use-join"><span>Whether to use <code v-pre>join()</code></span></a></h4>
<blockquote>
<p>Thread creation + Immediate call to <code v-pre>join()</code> -&gt; Procedure Call(程序调用)</p>
</blockquote>
<p>显然，我们通常会创建<strong>不止一个线程</strong>并等待其完成，否则使用线程就没有什么意义了。</p>
<p>我们需要注意的是，并非所有多线程代码都会使用到 <code v-pre>join()</code>。例如，多线程网络服务器可能会创建许多工作线程，然后使用主线程接受请求并将请求传递给工作线程执行**(线程池)**。因此，这种长寿命程序可能不需要使用 <code v-pre>join()</code>。</p>
<p>然而，创建线程来并行执行执行特定任务的程序可能会使用 <code v-pre>join()</code> 来确保在退出或进入下一阶段计算之前，当前阶段的所有工作都已完成。</p>
<h2 id="thread-locks" tabindex="-1"><a class="header-anchor" href="#thread-locks"><span>Thread Locks</span></a></h2>
<blockquote>
<p><code v-pre>mutex</code>：互斥锁</p>
</blockquote>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_mutex_unlock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>一个最基本的使用例子：</p>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#D8DEE9FF"> lock</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // 保持阻塞，直至该线程获取锁</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">x </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9FF"> x </span><span style="color:#81A1C1">+</span><span style="color:#B48EAD"> 1</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // or whatever your critical section is</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">pthread_mutex_unlock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // 释放锁</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这段代码看起来很简洁易懂符合常理，然而它存在着两个重要问题：</p>
<ol>
<li>缺少对锁对象的正确初始化——未初始化的锁很有可能使程序无法正确按照预期执行</li>
</ol>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#D8DEE9FF"> lock </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9FF"> PTHREAD_MUTEX_INITIALIZER</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // 直接使用全局默认的初始化锁对象</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#D8DEE9FF"> rc </span><span style="color:#81A1C1">=</span><span style="color:#88C0D0"> pthread_mutex_init</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> attr:</span><span style="color:#81A1C1">NULL</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // 进行动态初始化(携带参数)</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">assert</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">rc </span><span style="color:#81A1C1">==</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // always check successful init!</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">pthread_mutex_destory</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // 销毁锁</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li>在加锁和解锁的时候并没有检查返回值，从而导致潜在的错误发生</li>
</ol>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#5E81AC;font-weight:bold">#</span><span style="color:#81A1C1">include</span><span style="color:#ECEFF4"> &#x3C;</span><span style="color:#8FBCBB">pthread.h</span><span style="color:#ECEFF4">></span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// ------ Declarations ------</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_mutex_trylock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_mutex_unlock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// ------ Return Values ------</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// If successful, the pthread_mutex_lock() and pthread_mutex_unlock() functions return 0. </span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// Otherwise, an error number is returned to indicate the error.</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// The function pthread_mutex_trylock() returns 0 if a lock on the mutex object referenced by mutex is acquired. </span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// Otherwise, an error number is returned to indicate the error.</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#D8DEE9FF"> rc </span><span style="color:#81A1C1">=</span><span style="color:#88C0D0"> pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">assert</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">rc </span><span style="color:#81A1C1">==</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // always check lock successfully!</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然而每次执行类似操作时都需要进行校验有些不太美观，并且有些麻烦。因此在这类场景中，推荐使用包装方法来简化代码，同时提高程序健壮性：</p>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#81A1C1">void</span><span style="color:#88C0D0"> Pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    int</span><span style="color:#D8DEE9FF"> rc </span><span style="color:#81A1C1">=</span><span style="color:#88C0D0"> pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    assert</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">rc </span><span style="color:#81A1C1">==</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="condition-variables" tabindex="-1"><a class="header-anchor" href="#condition-variables"><span>Condition Variables</span></a></h2>
<p>在使用一些机器的时候，经常会看见外壳上加装了一些指示灯，它们可以用来指示当前机器的状态，我们可以根据机器状态来判断当前机器是否空闲、机器是否加工完成等等。</p>
<p>假如我们要使用这些机器来加工一些物品，一般流程是这样的：</p>
<ul>
<li>当机器空闲时，我们可以把待加工的原料放入机器中开始加工</li>
<li>然后开始等待机器加工完毕</li>
<li>直到机器加工完毕之后，再把成品取出</li>
<li>(Optional) 也许你会把上一步的成品送入到另外一个机器...</li>
</ul>
<p>在这些加工流程中，我们是根据什么来判断机器状态的呢？</p>
<p>没错，就是机器外壳的指示灯。它其实就是指示机器状态的<strong>条件变量(Condition Variables)。</strong></p>
<p>在线程之间的协作中，经常也会出现一个线程需要使用另几个线程结果的情况。这个线程可不能在其余线程完成工作之前就取走结果自顾自地执行了——它需要在合适的时机取出结果。这种时候通过条件变量就可以很方便地获取到其余线程的执行状态，并在合适的时机获取结果，之后顺利执行。</p>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_cond_wait</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_cond_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">cond</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">                      pthread_mutex_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">mutex</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#88C0D0"> pthread_cond_signal</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">pthread_cond_t</span><span style="color:#81A1C1"> *</span><span style="color:#D8DEE9">cond</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>注意：这些例程只有在**<u>持有锁</u>**的情况下才能使用！</p>
<p>并且，如果需要使用条件变量的话，需要将其和当前持有的锁进行绑定。</p>
</blockquote>
<div class="language-c line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="c" data-title="c"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-c"><code><span class="line"><span class="line"><span style="color:#616E88">// -- Thread 0 --</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">pthread_mutex_t</span><span style="color:#D8DEE9FF"> lock </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9FF"> PTHREAD_MUTEX_INITIALIZER</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">pthread_cond_t</span><span style="color:#D8DEE9FF"> cond </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9FF"> PTHREAD_COND_INITIALIZER</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">Pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// Critical Section</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// Q: Why using a loop instead a if statement here?</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">while</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9FF">ready </span><span style="color:#81A1C1">==</span><span style="color:#B48EAD"> 0</span><span style="color:#ECEFF4">)</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    Pthread_cond_wait</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">cond</span><span style="color:#ECEFF4">,</span><span style="color:#81A1C1"> &#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // The thread sleeps until the condition variable signs</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">Pthread_mutex_unlock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// -- Thread 1 --</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">Pthread_mutex_lock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// Critical Section</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">ready </span><span style="color:#81A1C1">=</span><span style="color:#B48EAD"> 1</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">Pthread_cond_signal</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">cond</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">Pthread_mutex_unlock</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">&#x26;</span><span style="color:#D8DEE9">lock</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在 Thread 0 中，初始化了一个锁对象以及一个条件变量对象。然后获取锁，之后等待条件变量改变，最后解锁。</p>
<p>Thread 1 中，同样获取了锁，然后改变 ready 这一全局变量的值，之后对条件变量发出信号，最后解锁。</p>
<details class="lake-collapse"><summary id="u4af3e63b"><span class="ne-text">Q：在上面的代码中，为什么锁能够被两个线程&quot;同时持有&quot;？</span></summary><p id="u0076b0f3" class="ne-p"><span class="ne-text">其实只是代码中没有显式说明锁的释放与重获得而已——锁始终只能被一个线程持有。</span></p><p id="udcad84ff" class="ne-p"><span class="ne-text">在等待条件变量改变信号的时候，调用等待方法的线程进入睡眠状态，同时该线程持有的锁也被暂时释放。</span></p><p id="u43e7797f" class="ne-p"><span class="ne-text">在监测到条件变量改变的时候，从 wait 方法返回之前，被唤醒的线程会重新获取锁。</span></p></details>
> Tips: 在线程之间进行同步时，尽可能使用条件变量而不是用简单的标志变量代替。
>
> 原因可以查看 [3.2 实现一个简单的join()?](https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/vwdnhvt4vq2gdsf3#FIbd8) 一节。
>
<blockquote>
<p>更新: 2024-10-23 11:18:09<br>
原文: <a href="https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/qlc9penlxxrgbss9" target="_blank" rel="noopener noreferrer">https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/qlc9penlxxrgbss9</a></p>
</blockquote>
</div></template>


