<template><div><h1 id="reading-2-basic-java" tabindex="-1"><a class="header-anchor" href="#reading-2-basic-java"><span>Reading 2: Basic Java</span></a></h1>
<h1 id="snapshot-diagrams-快照图" tabindex="-1"><a class="header-anchor" href="#snapshot-diagrams-快照图"><span>Snapshot Diagrams(快照图)</span></a></h1>
<p>快照图可以表示程序在某一个运行时的内部状态，包括它的栈(存储正在运行的方法和局部变量)和堆(存储当前已存在的对象)。</p>
<p>下面有一个比较简单的示例：</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> a</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 10</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">double</span><span style="color:#D8DEE9"> b</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 10.0</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9"> c</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">abcd</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">Point</span><span style="color:#D8DEE9"> p1</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> Point</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">10</span><span style="color:#ECEFF4">,</span><span style="color:#B48EAD"> 5</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // Point(double x, double y)</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/learning-path/MIT6.031/Notes/img/Z-oyJZamOHK-RkLH/1726919845287-a9a64302-68a8-4ac9-abc4-f6c6b9854913-515894.jpeg" alt="画板"></p>
<h1 id="mutating-values-vs-reassigning-variables" tabindex="-1"><a class="header-anchor" href="#mutating-values-vs-reassigning-variables"><span>Mutating values VS Reassigning variables</span></a></h1>
<p>快照图可以以一种直观的方式来区分更改值与重新分配变量的区别，我们有如下约定：</p>
<ul>
<li>当为变量或字段重新分配值时，改变当前变量箭头指向的对象为另一个值</li>
<li>当修改一个可修改对象的内容(如数组等)时，改变这个值对应的引用</li>
</ul>
<p>大致上可以分为以下几种具体情况：</p>
<h2 id="reassignment-and-immutable-values" tabindex="-1"><a class="header-anchor" href="#reassignment-and-immutable-values"><span>Reassignment and immutable values</span></a></h2>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9"> s</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">a</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">s </span><span style="color:#81A1C1">=</span><span style="color:#D8DEE9FF"> s </span><span style="color:#81A1C1">+</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">b</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">s </span><span style="color:#81A1C1">=</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">ab</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/learning-path/MIT6.031/Notes/img/Z-oyJZamOHK-RkLH/1726920698247-07fd4d66-d70f-4639-9143-b068362d851b-514561.png" alt="Snapshot Diagram of First Case"></p>
<p><code v-pre>String</code> 类型对象是<strong>不可修改</strong>的，因此 <code v-pre>s = s + &quot;b&quot;</code> 中，先由 <code v-pre>s + &quot;b&quot;</code> 生成了一个新的 <code v-pre>String</code> 类型对象， 再将变量 <code v-pre>s</code> 指向新生成的对象。</p>
<h2 id="mutable-values" tabindex="-1"><a class="header-anchor" href="#mutable-values"><span>Mutable values</span></a></h2>
<p>虽然<code v-pre>String</code> 类型对象是<strong>不可修改</strong>的，但是 <code v-pre>StringBuilder</code> 类型对象是可修改值的，该类型对象的值也代表了一个字符串。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#8FBCBB">StringBuilder</span><span style="color:#D8DEE9"> sb</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> StringBuilder</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">a</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">sb</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">append</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">b</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/learning-path/MIT6.031/Notes/img/Z-oyJZamOHK-RkLH/1726921251899-354467bf-d645-4fc1-a1c0-30af5b0aed5e-334700.png" alt="Mutable Obj"></p>
<p>可以看到，变量 <code v-pre>sb</code> 指向的对象并没有改变，但是对象值变了。</p>
<h2 id="unreassignable-references" tabindex="-1"><a class="header-anchor" href="#unreassignable-references"><span>Unreassignable references</span></a></h2>
<p>使用 <code v-pre>final</code> 关键字即可声明一个无法被再次赋值的变量，例如：</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">final</span><span style="color:#81A1C1"> int</span><span style="color:#D8DEE9"> n</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 5</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><img src="@source/learning-path/MIT6.031/Notes/img/Z-oyJZamOHK-RkLH/1726921536208-dee1f89b-6f71-44b3-9159-1e58d420d6c4-207369.png" alt="Final refer"></p>
<p>在变量 <code v-pre>n</code> 的整个生命周期中，它都无法被再次赋值了。如果你对这种类型的变量进行多次赋值，那么就会产生一个 <code v-pre>Compile Error</code>。在时序图中，为了展现出这种不可再次赋值性，我们可以使用双箭头来表明这是个无法再次赋值的变量。</p>
<p><img src="@source/learning-path/MIT6.031/Notes/img/Z-oyJZamOHK-RkLH/1726921750568-863a67eb-21d0-49ba-9fdd-9ef45db46298-547492.png" alt="Unreassignable 示例"></p>
<p>当然，下面的示例也是可行的：</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">final</span><span style="color:#8FBCBB"> StringBuilder</span><span style="color:#D8DEE9"> sb</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> StringBuilder</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">a</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">sb</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">append</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">bcde</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// it's okay, because the actual object the variable sb refers to didn't be reassigned.</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="exercise" tabindex="-1"><a class="header-anchor" href="#exercise"><span>Exercise</span></a></h2>
<font style="color:rgb(51, 51, 51);">Here is a function that mutates and reassigns its parameters:</font><div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">void</span><span style="color:#88C0D0"> f</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9FF"> s</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> StringBuilder</span><span style="color:#D8DEE9FF"> sb</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    s</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">concat</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">b</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9FF">    s </span><span style="color:#81A1C1">+=</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">c</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    sb</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">append</span><span style="color:#ECEFF4">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">d</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><font style="color:rgb(51, 51, 51);">Suppose it is called like this:</font><div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9"> t</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">a</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">StringBuilder</span><span style="color:#D8DEE9"> tb</span><span style="color:#81A1C1"> =</span><span style="color:#81A1C1"> new</span><span style="color:#88C0D0"> StringBuilder</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">t</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">f</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9FF">t</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9FF"> tb</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>
<font style="color:rgb(51, 51, 51);">After this code runs, what sequence of characters does </font>`<font style="color:rgb(51, 51, 51);background-color:rgb(245, 245, 245);">t</font>`<font style="color:rgb(51, 51, 51);"> refer to?</font></li>
<li>
<font style="color:rgb(51, 51, 51);">At the same point, what sequence of characters does </font>`<font style="color:rgb(51, 51, 51);background-color:rgb(245, 245, 245);">tb</font>`<font style="color:rgb(51, 51, 51);"> refer to?</font></li>
</ul>
<details class="lake-collapse"><summary id="u8c5cfc53"><span class="ne-text">Answer</span></summary><p id="uc9f727db" class="ne-p"><code class="ne-code"><span class="ne-text">t = &quot;a&quot;, tb = &quot;ad&quot;</span></code></p><p id="u18ac2944" class="ne-p" style="text-align: center"><img src="https://cdn.nlark.com/yuque/0/2024/png/48275148/1727006868257-94096e78-c289-4500-a6e7-d527831752ef.png" width="274.4" id="ue5814f4e" class="ne-image"></p><p id="u4034bb65" class="ne-p" style="text-align: center"><img src="https://cdn.nlark.com/yuque/0/2024/png/48275148/1727006852503-14b825a5-b581-4d74-8ad7-98ddfd5ce910.png" width="277.6" id="ua57786d6" class="ne-image"></p></details>
# `==` VS `equals()`
Java 中有两种方式来判断相等关系：
<ul>
<li><code v-pre>==</code> ：用于比较<strong>基本类型</strong>的值是否相等，例如 <code v-pre>5 == 5</code></li>
<li><code v-pre>equals()</code> ：用于比较不可修改类型或<strong>对象类型</strong>的值是否相等，例如 <code v-pre>&quot;abc&quot;.equals(&quot;abc)</code></li>
</ul>
<p>如果错误地使用 <code v-pre>equals()</code> 至基本类型的比对上(例如 <code v-pre>5.equals(5)</code>，Java 会在 Static check 阶段就检查出错误。但是如果将 <code v-pre>==</code> 用于对象类型的比对上，Java 则<strong>不会</strong>抛出 Static error，但是结果可能与你预期的结果大相径庭——因为 <code v-pre>==</code> 被用于对象类型的比对时，它被重载为检查这组待比对的值是否指向<strong>同一个对象。</strong></p>
<p><img src="@source/learning-path/MIT6.031/Notes/img/Z-oyJZamOHK-RkLH/1727007580031-c109fa46-202d-4d0a-bd3b-456d2a5681d3-846722.png" alt="Example of == and equals()"></p>
<p>对上面的快照图中呈现的状态，执行下列运算：</p>
<ul>
<li><code v-pre>x.equals(y)</code> -&gt; <code v-pre>True</code>：Their values are equal</li>
<li><code v-pre>x.equals(z)</code> -&gt; <code v-pre>True</code>：The same reason</li>
<li><code v-pre>x == z</code> -&gt; <code v-pre>False</code>：<code v-pre>x</code> and <code v-pre>z</code> don't refer to the same object.</li>
<li><code v-pre>x == y</code> -&gt; <code v-pre>True</code> ： <code v-pre>x</code> and <code v-pre>y</code> do refer to the same object.</li>
</ul>
<p>由此可以得到一个大体的使用规则：</p>
<ul>
<li>
<font style="color:rgb(51, 51, 51);">Use </font>`<font style="background-color:rgb(245, 245, 245);">==</font>`<font style="color:rgb(51, 51, 51);"> for comparing </font>**<font style="color:rgb(51, 51, 51);">primitive</font>**<font style="color:rgb(51, 51, 51);"> values, like ints, chars, and doubles.</font></li>
<li>
<font style="color:rgb(51, 51, 51);">Use </font>`<font style="background-color:rgb(245, 245, 245);">equals()</font>`<font style="color:rgb(51, 51, 51);"> for comparing </font>**<font style="color:rgb(51, 51, 51);">object</font>**<font style="color:rgb(51, 51, 51);"> values, like lists, arrays, strings, and other objects.</font></li>
</ul>
<h1 id="java-collections" tabindex="-1"><a class="header-anchor" href="#java-collections"><span><font style="color:rgb(51, 51, 51);">Java Collections</font></span></a></h1>
<blockquote>
<p>本部分在讲 Java 集合相关的常用方法等基本内容，故略过</p>
</blockquote>
<h1 id="enumerations" tabindex="-1"><a class="header-anchor" href="#enumerations"><span>Enumerations</span></a></h1>
<p>Benefits using enumerations:</p>
<ul>
<li>more typesafe</li>
<li>prevents mistakes like type mismatches and misspellings</li>
</ul>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">int</span><span style="color:#D8DEE9"> month</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9FF"> TUESDAY</span><span style="color:#81A1C1">;</span><span style="color:#616E88">  //  no error if integers are used</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">Month</span><span style="color:#D8DEE9"> month</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> DayOfWeek</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">TUESDAY</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // static error if enumerations are used </span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">String</span><span style="color:#D8DEE9"> color</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">REd</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span><span style="color:#616E88">        // no error, misspelling isn't caught</span></span></span>
<span class="line"><span class="line"><span style="color:#8FBCBB">PenColor</span><span style="color:#D8DEE9"> drawingColor</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> PenColor</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">REd</span><span style="color:#81A1C1">;</span><span style="color:#616E88"> // static error when enumeration value is misspelled</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="java-api-documention" tabindex="-1"><a class="header-anchor" href="#java-api-documention"><span>Java API Documention</span></a></h1>
<p>The JDK 21's API documention is <a href="https://docs.oracle.com/en/java/javase/21/docs/api/" target="_blank" rel="noopener noreferrer">here</a>.</p>
<blockquote>
<p>更新: 2024-09-23 08:23:07<br>
原文: <a href="https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/ybmgc7v0z0urgdfk" target="_blank" rel="noopener noreferrer">https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/ybmgc7v0z0urgdfk</a></p>
</blockquote>
</div></template>


