<template><div><h1 id="reading-3-testing" tabindex="-1"><a class="header-anchor" href="#reading-3-testing"><span>Reading 3: Testing</span></a></h1>
<h1 id="test-first-programming" tabindex="-1"><a class="header-anchor" href="#test-first-programming"><span>Test-first programming</span></a></h1>
<font style="color:rgb(51, 51, 51);">In </font>_<font style="color:rgb(0, 0, 0);">test-first programming</font>_<font style="color:rgb(51, 51, 51);">, you write the spec and the tests before you even write any code. The development of a single function proceeds in this order:</font><ol>
<li><strong><font style="color:rgb(51, 51, 51);">Spec</font></strong><font style="color:rgb(51, 51, 51);">: Write a specification for the function.</font></li>
<li><strong><font style="color:rgb(51, 51, 51);">Test</font></strong><font style="color:rgb(51, 51, 51);">: Write tests that exercise the specification.</font></li>
<li><strong><font style="color:rgb(51, 51, 51);">Implement</font></strong><font style="color:rgb(51, 51, 51);">: Write the implementation.</font></li>
</ol>
<font style="color:rgb(51, 51, 51);">Once your implementation passes the tests you wrote, you're done.</font><h1 id="systematic-testing" tabindex="-1"><a class="header-anchor" href="#systematic-testing"><span><font style="color:rgb(51, 51, 51);">Systematic Testing</font></span></a></h1>
<p>穷举、随意或随机测试在对软件测试方面的表现都不尽人意，所以我们需要系统化测试。系统化测试意味着有原则的挑选测试用例，同时设计出具有如下三种理想属性的测试集：</p>
<ul>
<li><strong><font style="color:rgb(51, 51, 51);">Correct</font></strong><font style="color:rgb(51, 51, 51);">. A correct test suite is a legal client of the specification, and it accepts </font><strong><font style="color:rgb(51, 51, 51);">all</font></strong><font style="color:rgb(51, 51, 51);"> legal implementations of the spec without complaint. This gives us the freedom to change how the module is implemented internally without necessarily having to change the test suite.</font></li>
<li><strong><font style="color:rgb(51, 51, 51);">Thorough</font></strong><font style="color:rgb(51, 51, 51);">. A thorough test suite finds </font><strong><font style="color:rgb(51, 51, 51);">actual</font></strong><font style="color:rgb(51, 51, 51);"> bugs in the implementation, caused by mistakes that programmers are likely to make.</font></li>
<li><strong><font style="color:rgb(51, 51, 51);">Small</font></strong><font style="color:rgb(51, 51, 51);">. A small test suite, with few test cases, is </font><strong><font style="color:rgb(51, 51, 51);">faster</font></strong><font style="color:rgb(51, 51, 51);"> to write in the first place, and </font><strong><font style="color:rgb(51, 51, 51);">easier</font></strong><font style="color:rgb(51, 51, 51);"> to update if the specification evolves. Small test suites are also faster to run. You will be able to run your tests more frequently if your test suites are small and fast.</font></li>
</ul>
<h3 id="划分测试用例" tabindex="-1"><a class="header-anchor" href="#划分测试用例"><span><font style="color:rgb(51, 51, 51);">划分测试用例</font></span></a></h3>
<p>将输入选区依据一定原则划分成若干块<strong>不互相覆盖</strong>的区域，划分过后再从各个区域中选一个测试用例以组成测试用例集。这样处理过后的用例集更可能拥有上面提及的三种理想属性。</p>
<p>就像 jyy 老师在<a href="https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/fn885gf3a1e9t4m4#DoIkr" target="_blank" rel="noopener noreferrer">绪论 4</a> 中给出的启发一样，我们可以利用待测试程序本身的性质来编写测试用例。</p>
<h4 id="example-测试math-abs-方法" tabindex="-1"><a class="header-anchor" href="#example-测试math-abs-方法"><span>Example: 测试<code v-pre>Math.abs()</code> 方法</span></a></h4>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">/**</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"> * ...</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"> * </span><span style="color:#8FBCBB">@param</span><span style="color:#D8DEE9"> a</span><span style="color:#616E88">  the argument whose absolute value is to be determined</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"> * </span><span style="color:#8FBCBB">@return</span><span style="color:#616E88"> the absolute value of the argument.</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"> */</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> static</span><span style="color:#81A1C1"> int</span><span style="color:#88C0D0"> abs</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">int</span><span style="color:#D8DEE9FF"> a</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    // ...</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727174439331-65372c10-d635-41be-8724-78e6fdac7d02-059422.jpeg" alt="画板"></p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// partition: a >= 0; a &#x3C; 0</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>所以，我们从这两个选区中各选择一个测试用例组成测试集即可，例如：</p>
<ul>
<li>$ a &lt; 0 $：我们选取 <code v-pre>a = -3</code> 作为一个测试用例</li>
<li>$ a \geq 0 $：我们选取 <code v-pre>a = 999</code> 作为一个测试用例</li>
</ul>
<h4 id="分区相关的一些描述词" tabindex="-1"><a class="header-anchor" href="#分区相关的一些描述词"><span>分区相关的一些描述词</span></a></h4>
<ul>
<li><code v-pre>Disjoint</code>：不相交的</li>
<li><code v-pre>Complete</code>：完整的，这里表示完整地覆盖原输入集
<ul>
<li>一个<strong>合法</strong>的分区方案<strong>一定</strong>要符合的性质</li>
</ul>
</li>
<li><code v-pre>Correct</code>：正确的，表示输入符合待测试程序的 <code v-pre>specification</code></li>
</ul>
<h3 id="将边界条件涵盖在分区中" tabindex="-1"><a class="header-anchor" href="#将边界条件涵盖在分区中"><span>将边界条件涵盖在分区中</span></a></h3>
<p>不论是日常开发还是跟 OJ 斗得你死我活的时候，边界条件总是很容易引发 bug：</p>
<ul>
<li>正负数的临界点 - 0</li>
<li>数值类型的最值：<code v-pre>INT_MAX</code>, etc.</li>
<li>空集合</li>
<li>序列的首尾元素</li>
</ul>
<h4 id="再遇-math-abs" tabindex="-1"><a class="header-anchor" href="#再遇-math-abs"><span>再遇 <code v-pre>Math.abs()</code></span></a></h4>
<p>其实 2.2.1 节中给出的 <code v-pre>abs</code> 方法的 <code v-pre>specificaion</code> 并不是完整的，实际上，<code v-pre>abs</code> 方法的完整描述如下：</p>
<p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727176301021-d4d0c135-99c3-40de-96c7-189169fffae3-271292.png" alt="Math.abs() 方法的完整内容"></p>
<p>描述中明确提到了一个值——<code v-pre>Integer.MIN_VALUE</code>，当输入的参数为该值时，结果会与一般情况不同。</p>
<p>我们自己写了一个测试方法来测试 <code v-pre>abs</code> 方法返回结果与描述中的一致性：</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#8FBCBB"> org</span><span style="color:#ECEFF4">.</span><span style="color:#8FBCBB">testng</span><span style="color:#ECEFF4">.</span><span style="color:#8FBCBB">annotations</span><span style="color:#ECEFF4">.</span><span style="color:#8FBCBB">Test</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#81A1C1"> static</span><span style="color:#8FBCBB"> org</span><span style="color:#ECEFF4">.</span><span style="color:#8FBCBB">junit</span><span style="color:#ECEFF4">.</span><span style="color:#8FBCBB">jupiter</span><span style="color:#ECEFF4">.</span><span style="color:#8FBCBB">api</span><span style="color:#ECEFF4">.</span><span style="color:#8FBCBB">Assertions</span><span style="color:#ECEFF4">.</span><span style="color:#81A1C1">*;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> MainTest</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">Test</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#81A1C1"> void</span><span style="color:#88C0D0"> testMath</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">1</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">abs</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">1</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">2</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">abs</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">-</span><span style="color:#B48EAD">2</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">0</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">abs</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">0</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">Integer</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">MIN_VALUE</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">abs</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">Integer</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">MIN_VALUE</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">Integer</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">MAX_VALUE</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">abs</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">Integer</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">MAX_VALUE</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">        // Test passes when the statement below is commented out.</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertNotEquals</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">Integer</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">MIN_VALUE</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">abs</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">Integer</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">MIN_VALUE</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">        // org.opentest4j.AssertionFailedError: </span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">        // expected: not equal but was: &#x3C;-2147483648></span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>所以从 <a href="#rNXfj">2.1.1 节</a> 根据分区确定的测试用例集的基础上，我们可以加入如下的边界条件：</p>
<ul>
<li>$ a = 0 $</li>
<li><code v-pre>a = Integer.MAX_VALUE</code></li>
<li><code v-pre>a = Integer.MIN_VALUE</code>：注意，这和其余任何输入产生的行为均不同！</li>
</ul>
<p>这样调整过后，我们对 <code v-pre>abs</code> 方法的输入分区如下：</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// partition:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//     a = Integer.MIN_VALUE</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//     Integer.MIN_VALUE &#x3C; a &#x3C; 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//     a = 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//     0 &#x3C; a &#x3C; Integer.MAX_VALUE</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//     a = Integer.MAX_VALUE</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="example-biginteger-multiply" tabindex="-1"><a class="header-anchor" href="#example-biginteger-multiply"><span>Example: <code v-pre>BigInteger.multiply()</code></span></a></h4>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">/**</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"> * </span><span style="color:#8FBCBB">@param</span><span style="color:#D8DEE9"> val</span><span style="color:#616E88"> another BigInteger</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"> * </span><span style="color:#8FBCBB">@return</span><span style="color:#616E88"> a BigInteger whose value is (this * val).</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88"> */</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#8FBCBB"> BigInteger</span><span style="color:#88C0D0"> multiply</span><span style="color:#ECEFF4">(</span><span style="color:#8FBCBB">BigInteger</span><span style="color:#D8DEE9FF"> val</span><span style="color:#ECEFF4">)</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>根据乘法的一些性质，我们可以把输入用例大致分成几种情况：</p>
<blockquote>
<p>假设 <code v-pre>a</code> 与 <code v-pre>b</code> 均为 <code v-pre>BigInteger</code> 对象</p>
</blockquote>
<ul>
<li>$ a &gt; 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>，</mtext></mrow><annotation encoding="application/x-tex">，</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">，</span></span></span></span> b &gt; 0 $</li>
<li>$ a &gt; 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>，</mtext></mrow><annotation encoding="application/x-tex">，</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">，</span></span></span></span> b &lt; 0 $</li>
<li>$ a &lt; 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>，</mtext></mrow><annotation encoding="application/x-tex">，</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">，</span></span></span></span> b &gt; 0 $</li>
<li>$ a &lt; 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>，</mtext></mrow><annotation encoding="application/x-tex">，</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">，</span></span></span></span> b &gt; 0 $</li>
<li>不要忘了<strong>边界</strong>条件：$ a =0 $<code v-pre>||</code> $ b = 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>；</mtext></mrow><annotation encoding="application/x-tex">；</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">；</span></span></span></span> a = 1 $ <code v-pre>||</code> $ b = 1 $</li>
<li>如果再考虑上常规数值类型的<strong>最值</strong>呢？</li>
</ul>
<p>这样分区以后，我们一共得到了$ 6 \times 6 = 36 $种子区域。</p>
<p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727178136747-a48ca7a1-fd43-455e-b58e-de70b8758e80-058341.png" alt="我们得到的分区-直观表示"></p>
<h3 id="using-multiple-partitions" tabindex="-1"><a class="header-anchor" href="#using-multiple-partitions"><span>Using Multiple Partitions</span></a></h3>
<p>可以看到，如果只使用一种分区的话，即使是只有两个参数的方法，也有多达 36 种分区情况，所以你可能会猜测，单类分区的分区情况总数可能会达到$ x ^ y <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>这个量级。也就是说，当参数个数</mtext></mrow><annotation encoding="application/x-tex">这个量级。也就是说，当参数个数</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">这个量级。也就是说，当参数个数</span></span></span></span> x <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>以及单个参数对应的分界区域</mtext></mrow><annotation encoding="application/x-tex">以及单个参数对应的分界区域</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">以及单个参数对应的分界区域</span></span></span></span> y $多了以后，这个情况总数(它直接关系到测试集内的用例数量)会成指数级增长。这是我们不希望看到的——测试用例集应该是一个规模较小的集合。</p>
<p>还是拿 <a href="#NCfCz">2.2.2 节</a> 中介绍的例子 <code v-pre>BigInteger.multiply()</code>来说。我们之前只把参数的分区情况独立化了，但是有些情况下不同分区的预期结果是一致的，例如$ a = 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>，</mtext></mrow><annotation encoding="application/x-tex">，</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">，</span></span></span></span> b \neq 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>与</mtext></mrow><annotation encoding="application/x-tex">与</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">与</span></span></span></span> b = 0 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>，</mtext></mrow><annotation encoding="application/x-tex">，</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">，</span></span></span></span> a = 0 $这两种分区的预期结果是一致的(或者说，<strong>有共性</strong>的)。原本测试集中所涵盖的测试用例存在一些输入不同但预期结果“相同”的情况，因此，为了缩减测试用例集的规模，我们也许自然而然地就想着把这些结果一致的情况<strong>合并</strong>起来。</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// partition on a:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a = 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a = 1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is small integer > 1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is small integer &#x3C; 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is large positive integer</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is large negative integer</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//      (where "small" fits in long, and "large" doesn't)</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// partition on b:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   b = 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   b = 1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   b is small integer > 1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   b is small integer &#x3C; 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   b is large positive integer</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   b is large negative integer</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// partition on signs of a and b:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//    a and b are both positive</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//    a and b are both negative</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//    a positive and b negative</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//    a negative and b positive</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//    one or both are 0</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727179063901-34bd1ab9-a08a-4422-8561-9b5a6642c8e4-270827.png" alt="合并后的分区图"></p>
<p>我们的分区规模从原先的$ 36 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>个缩减到了现在的</mtext></mrow><annotation encoding="application/x-tex">个缩减到了现在的</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">个缩减到了现在的</span></span></span></span> 6 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>个，这意味着测试集规模也可从原先的</mtext></mrow><annotation encoding="application/x-tex">个，这意味着测试集规模也可从原先的</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">个，这意味着测试集规模也可从原先的</span></span></span></span> 36 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>个缩减至</mtext></mrow><annotation encoding="application/x-tex">个缩减至</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord cjk_fallback">个缩减至</span></span></span></span> 6 $个**<u>精心挑选</u>**的测试用例。</p>
<h4 id="exercise-covering-every-subdomain-vs-covering-cartesian-product" tabindex="-1"><a class="header-anchor" href="#exercise-covering-every-subdomain-vs-covering-cartesian-product"><span>Exercise: Covering every subdomain vs. covering Cartesian product</span></a></h4>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// partition on a:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a = 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a = 1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is small integer > 1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is small integer &#x3C; 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is large positive integer</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//   a is large negative integer</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//      (where "small" fits in long, and "large" doesn't)</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这个分区有六个子域，因此需要六个不同的值来组成测试用例集。</p>
<p>如果我们用下面的分区规则来替代上面的分区：</p>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#616E88">// partition on a: 0, positive, negative</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// partition on a: 1, !=1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// partition on a: small (fits in long), large (doesn't fit in long)</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Q1</strong>: 如果想要囊括这三个分区对应的<strong>各个</strong>子域中的情况，<strong>至少</strong>需要几个值？</p>
<details class="lake-collapse"><summary id="u27c80bea"><span class="ne-text">Answer for Q1</span></summary><p id="ub1c09709" class="ne-p"><span class="ne-text">至少需要 3 个值，例如：</span></p><ul class="ne-ul"><li id="u663cb0d8" data-lake-index-type="0"><span id="J6Axi" class="ne-math"><img src="https://cdn.nlark.com/yuque/__latex/f8d659399fdedbe794e6076d711b24fc.svg"></span><span class="ne-text">：满足 </span><code class="ne-code"><span class="ne-text">0, != 1, small</span></code><span class="ne-text">三个子域的情况</span></li><li id="u6ed0c941" data-lake-index-type="0"><span id="auGow" class="ne-math"><img src="https://cdn.nlark.com/yuque/__latex/b98135bc0b5d8a1ad94e786c696d17f3.svg"></span><span class="ne-text">：满足 </span><code class="ne-code"><span class="ne-text">1, positive</span></code><span class="ne-text"> 两个子域的情况</span></li><li id="u227358e4" data-lake-index-type="0"><span id="qFt32" class="ne-math"><img src="https://cdn.nlark.com/yuque/__latex/5e31d239d5f87b025eacf2a09d20f143.svg"></span><span class="ne-text">：满足 </span><code class="ne-code"><span class="ne-text">negetive, large</span></code><span class="ne-text"> 两个子域的情况</span></li></ul><p id="u692c6562" class="ne-p"><span class="ne-text">所以至少需要 3 个值.</span></p></details>
**Q2**：如果想要囊括这三个分区**做笛卡尔积之后**的各个子域的情况，至少需要几个值？
<details class="lake-collapse"><summary id="u9e541f43"><span class="ne-text">Answer for Q2</span></summary><p id="ufe899d1c" class="ne-p"><span class="ne-text">首先我们要搞清楚这三个分区做笛卡尔积之后的子域划分情况：</span></p><pre data-language="java" id="Qww8i" class="ne-codeblock language-java"><code>// partition on a:
// 1. a = 0
// 2. a = 1
// 3. a &lt; 0 &amp;&amp; a &gt;= Long.MIN_VALUE
// 4. a &lt; Long.MIN_VALUE
// 5. a &gt; 0 &amp;&amp; a &lt;= Long.MAX_VALUE
// 6. a &gt; Long.MAX_VALUE</code></pre><p id="u69530008" class="ne-p"><span class="ne-text">一共是六个不相互覆盖的子域，且该划分是完整的。</span></p><p id="u0fd9a043" class="ne-p"><span class="ne-text">因此至少需要 6 个值。</span></p></details>
### 记录下你的测试策略
在创建测试集的过程中，记录下你的测试策略是一个很好的想法。一般来说，测试策略可以从以下三个方面来描述：
<ul>
<li>分区情况</li>
<li>分区对应的子域列表</li>
<li>各个测试用例覆盖子域的情况</li>
</ul>
<div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> MaxTest</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    /*</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   * Testing strategy</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   * partition:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *    a &#x3C; b</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *    a > b</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *    a = b</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   */</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    // covers a &#x3C; b</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">Test</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#81A1C1"> void</span><span style="color:#88C0D0"> testALessThanB</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">2</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> Math</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">max</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">1</span><span style="color:#ECEFF4">,</span><span style="color:#B48EAD"> 2</span><span style="color:#ECEFF4">))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-java line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="java" data-title="java"><pre v-pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff language-java"><code><span class="line"><span class="line"><span style="color:#81A1C1">public</span><span style="color:#81A1C1"> class</span><span style="color:#8FBCBB"> Multiply</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    /*</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   * Testing strategy</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   * cover the cartesian product of these partitions:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *   partition on a: positive, negative, 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *   partition on b: positive, negative, 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *   partition on a: 1, !=1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *   partition on b: 1, !=1</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *   partition on a: small (fits in a long value), or large (doesn't fit)</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *   partition on b: small, large</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   * </span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   * cover the subdomains of these partitions:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *   partition on signs of a and b:</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *      both positive</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *      both negative</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *      different signs</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   *      one or both are 0</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">   */</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    // covers a is positive, b is negative, </span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    //        a fits in long value, b fits in long value,</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    //        a and b have different signs</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">Test</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#81A1C1"> void</span><span style="color:#88C0D0"> testDifferentSigns</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BigInteger</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">-</span><span style="color:#B48EAD">146</span><span style="color:#ECEFF4">),</span><span style="color:#D8DEE9"> BigInteger</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">73</span><span style="color:#ECEFF4">).</span><span style="color:#88C0D0">multiply</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BigInteger</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#81A1C1">-</span><span style="color:#B48EAD">2</span><span style="color:#ECEFF4">)))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">    // covers a = 1, b != 1, a and b have same sign</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    @</span><span style="color:#D08770">Test</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    public</span><span style="color:#81A1C1"> void</span><span style="color:#88C0D0"> testIdentity</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        assertEquals</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BigInteger</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">33</span><span style="color:#ECEFF4">),</span><span style="color:#D8DEE9"> BigInteger</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">1</span><span style="color:#ECEFF4">).</span><span style="color:#88C0D0">multiply</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">BigInteger</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">valueOf</span><span style="color:#ECEFF4">(</span><span style="color:#B48EAD">33</span><span style="color:#ECEFF4">)))</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="black-box-and-glass-box-testing" tabindex="-1"><a class="header-anchor" href="#black-box-and-glass-box-testing"><span>Black-box and glass-box testing</span></a></h3>
<ul>
<li><strong>黑盒测试(Black box test)<strong>是指</strong>只</strong>通过待测试内容的描述(<code v-pre>specification</code>)来设计测试用例集。</li>
<li><strong>“白”盒测试(Glass box test)<strong>是指根据待测试内容的</strong>具体实现</strong>来设计相关的测试用例。如果待测试内容内部根据输入用例的不同选择不同的算法策略来进行实现，这种时候白盒测试就能测试地更为<strong>充分</strong>(Through)。</li>
</ul>
<h3 id="代码覆盖率-coverage" tabindex="-1"><a class="header-anchor" href="#代码覆盖率-coverage"><span>代码覆盖率(Coverage)</span></a></h3>
<p>覆盖率是衡量一个测试用例集对待测试内容的测试<strong>全面性</strong> (Through) 的重要指标。</p>
<p>一般来说，覆盖率主要有以下三种：</p>
<ul>
<li><strong><font style="color:rgb(51, 51, 51);">Statement(</font><strong><strong><u><font style="color:rgb(51, 51, 51);">语句</font></u></strong></strong><font style="color:rgb(51, 51, 51);">) coverage</font></strong><font style="color:rgb(51, 51, 51);">: is </font><strong><font style="color:rgb(51, 51, 51);">every statement</font></strong><font style="color:rgb(51, 51, 51);"> run by some test case? </font><strong><font style="color:rgb(51, 51, 51);">(a common goal)</font></strong></li>
<li><strong><font style="color:rgb(51, 51, 51);">Branch(</font><strong><strong><u><font style="color:rgb(51, 51, 51);">分支</font></u></strong></strong><font style="color:rgb(51, 51, 51);">) coverage</font></strong><font style="color:rgb(51, 51, 51);">: for every </font><code v-pre>&lt;font style=&quot;background-color:rgb(245, 245, 245);&quot;&gt;if&lt;/font&gt;</code><font style="color:rgb(51, 51, 51);"> or </font><code v-pre>&lt;font style=&quot;background-color:rgb(245, 245, 245);&quot;&gt;while&lt;/font&gt;</code><font style="color:rgb(51, 51, 51);"> statement in the program, are </font><strong><font style="color:rgb(51, 51, 51);">both the true and the false direction</font></strong><font style="color:rgb(51, 51, 51);"> taken by some test case? </font><strong><font style="color:rgb(51, 51, 51);">(highly desirable)</font></strong></li>
<li><strong><font style="color:rgb(51, 51, 51);">Path(</font><strong><strong><u><font style="color:rgb(51, 51, 51);">程序执行路径</font></u></strong></strong><font style="color:rgb(51, 51, 51);">) coverage</font></strong><font style="color:rgb(51, 51, 51);">: is every possible combination of branches — </font><strong><font style="color:rgb(51, 51, 51);">every path</font></strong><font style="color:rgb(51, 51, 51);"> through the program — taken by some test case? </font><strong><font style="color:rgb(51, 51, 51);">(infeasible)</font></strong></li>
</ul>
<font style="color:rgb(51, 51, 51);">就测试效果以及测试规模来说，</font>$ Path > Branch > Statement $<font style="color:rgb(51, 51, 51);">。</font><font style="color:rgb(51, 51, 51);">幸运的是，我们已经有了统计并展示覆盖率的工具，这项工具内置于 IDEA 中，只需右键你想要运行的程序代码，并且选择 </font>`<font style="color:rgb(51, 51, 51);">RunWithCoverage</font>`<font style="color:rgb(51, 51, 51);"> 选项即可。</font><p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727254145503-b39c22ef-191b-4e45-99f6-183c354b6010-320225.png" alt="以展示覆盖率的方式来运行程序"></p>
<p>运行之后就可以看到当次执行的各项覆盖率：</p>
<p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727256572190-da4078a5-1034-4b89-9dc3-44ef00740cee-529479.png" alt="覆盖率统计示例"></p>
<p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727256806790-24f1b6f9-2de5-4c12-81ac-efccb2644f1d-788864.png" alt="黄色语句示例-1"></p>
<p><img src="@source/learning-path/MIT6.031/Notes/img/KzmHEl-dz2PoOdWB/1727256940749-b78df58f-b9f0-493a-8d59-0ca903330612-931567.png" alt="黄色语句示例-2"></p>
<p>根据上面的观察，我们可以把三类颜色代表的含义简要的解释如下：</p>
<ul>
<li>绿色：对于一般语句来说：运行过程中均被执行；对于条件来说：条件的各类情况均被覆盖到。</li>
<li>黄色：测试情况单一，未覆盖到全部情况</li>
<li>红色：测试过程中完全没被执行到的语句。</li>
</ul>
<blockquote>
<p>更新: 2024-09-25 19:56:07<br>
原文: <a href="https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/dx4zdza1ypec9ovt" target="_blank" rel="noopener noreferrer">https://www.yuque.com/yuqueyonghukaqxkk/self_learning_route/dx4zdza1ypec9ovt</a></p>
</blockquote>
</div></template>


